/**
 * Seed script to add Startup & VC Events to the CRM
 * Research date: March 31, 2026
 *
 * Focus: Events within 3 hours of Amsterdam, Apr-Sep 2026
 * LoreWeaver angle: Fundraising, investor networking, startup community
 *
 * Sources:
 * - Startup Amsterdam (iamsterdam.com)
 * - Techleap.nl
 * - NVP (Dutch PE/VC Association)
 * - Eventbrite
 * - Meetup
 *
 * Run with: npx ts-node src/seed-startup-vc-events.ts
 */

import * as admin from "firebase-admin";
import { Timestamp } from "firebase-admin/firestore";

// Initialize Firebase Admin with explicit project ID
if (!admin.apps.length) {
  admin.initializeApp({
    projectId: "loreweaver-crm",
  });
}

const db = admin.firestore();

interface StartupEvent {
  name: string;
  type: "conference" | "meetup" | "workshop" | "awards" | "online" | "dinner" | "pitch";
  startDate: Date;
  endDate?: Date;
  time?: string;
  location: string;
  venue?: string;
  country: string;
  website: string;
  ticketUrl?: string;
  cost: string;
  expectedAudience: string;
  loreWeaverScore: number;
  loreWeaverReason: string;
  organizer: string;
  contacts?: { name: string; email: string; role: string }[];
  tags: string[];
  notes: string;
  priority: "high" | "medium" | "low";
  status: "upcoming" | "past" | "cancelled";
  investorAccess: boolean;
  pitchOpportunity: boolean;
}

const startupVCEvents: StartupEvent[] = [
  // HIGH PRIORITY - INVESTOR ACCESS EVENTS
  {
    name: "Techleap Community Founder/CEO Dinner",
    type: "dinner",
    startDate: new Date("2026-04-15"),
    time: "18:30-21:30",
    location: "Amsterdam",
    venue: "Umami by Han Amsterdam, Overtoom 31HS",
    country: "Netherlands",
    website: "https://platform.techleap.nl/events/techleap-community-founderceo-dinner-kjug",
    cost: "Free (invite-only)",
    expectedAudience: "20-40 founders & CEOs",
    loreWeaverScore: 10,
    loreWeaverReason: "Intimate setting with founders & CEOs, ideal for relationship building pre-fundraise",
    organizer: "Techleap",
    tags: ["founders", "ceo", "networking", "invite-only", "techleap"],
    notes: "Curated dinner for Techleap Community founders & CEOs. Requires Techleap membership.",
    priority: "high",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: false,
  },
  {
    name: "Investor Connect: Pitch & Networking — Amsterdam",
    type: "pitch",
    startDate: new Date("2026-04-15"),
    time: "18:00",
    location: "Amsterdam",
    venue: "I Dock",
    country: "Netherlands",
    website: "https://www.eventbrite.com/e/investor-connect-pitch-networking-amsterdam-tickets-1984846532409",
    cost: "€10-15",
    expectedAudience: "50-100 founders & investors",
    loreWeaverScore: 9,
    loreWeaverReason: "Direct pitch opportunity to investors",
    organizer: "Startup Events Amsterdam",
    tags: ["pitch", "investors", "networking", "funding"],
    notes: "Pitch your startup to investors. Bring pitch deck.",
    priority: "high",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: true,
  },
  {
    name: "AI020 2026",
    type: "conference",
    startDate: new Date("2026-04-16"),
    time: "09:00-21:00",
    location: "Amsterdam",
    venue: "Koninklijk Instituut voor de Tropen",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/ai020-2026",
    cost: "TBA",
    expectedAudience: "500+ AI professionals",
    loreWeaverScore: 9,
    loreWeaverReason: "Amsterdam's AI community event, great for narrative AI positioning",
    organizer: "Startup Amsterdam",
    tags: ["ai", "conference", "amsterdam", "tech"],
    notes: "Major Amsterdam AI event. Perfect for positioning LoreWeaver in the AI space.",
    priority: "high",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: false,
  },
  {
    name: "0100 Europe 2026",
    type: "conference",
    startDate: new Date("2026-04-21"),
    endDate: new Date("2026-04-23"),
    location: "Amsterdam",
    venue: "Leonardo Royal Hotel Amsterdam",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/0100-europe-2026",
    cost: "€500-1500",
    expectedAudience: "500+ VCs, founders, LPs",
    loreWeaverScore: 8,
    loreWeaverReason: "Major European VC conference",
    organizer: "0100 Conferences",
    tags: ["vc", "conference", "investors", "europe"],
    notes: "Major European VC conference. High ticket price but excellent investor access.",
    priority: "high",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: true,
  },
  {
    name: "The Dutch Startup Meetup 2026",
    type: "meetup",
    startDate: new Date("2026-04-23"),
    time: "18:00-22:00",
    location: "Amsterdam",
    venue: "Register to see address",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/the-dutch-startup-meetup-2026",
    cost: "TBA",
    expectedAudience: "200-500 startup community members",
    loreWeaverScore: 8,
    loreWeaverReason: "Networking with Dutch startup community",
    organizer: "Startup Amsterdam",
    tags: ["startup", "meetup", "networking", "dutch"],
    notes: "Major Dutch startup networking event.",
    priority: "high",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },
  {
    name: "Nursery Presents: Building a Funding Roadmap",
    type: "workshop",
    startDate: new Date("2026-05-21"),
    time: "15:00",
    location: "Amsterdam",
    venue: "Startup Village",
    country: "Netherlands",
    website: "https://www.eventbrite.nl/e/nursery-presents-building-a-funding-roadmap-tickets-1978225393404",
    cost: "Free",
    expectedAudience: "30-50 founders",
    loreWeaverScore: 9,
    loreWeaverReason: "Directly relevant for funding strategy",
    organizer: "Startup Village / Nursery",
    tags: ["funding", "workshop", "strategy", "startup-village"],
    notes: "Free workshop on building a funding roadmap. Very relevant pre-fundraise.",
    priority: "high",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },
  {
    name: "Apex Venture & Tech Connect Days",
    type: "conference",
    startDate: new Date("2026-06-11"),
    time: "09:00",
    location: "Santpoort-Noord",
    venue: "Landgoed Duin & Kruidberg",
    country: "Netherlands",
    website: "https://www.eventbrite.com/e/apex-venture-tech-connect-days-in-amsterdam-netherlands-tickets-1979012475588",
    cost: "TBA",
    expectedAudience: "100-200 founders & investors",
    loreWeaverScore: 8,
    loreWeaverReason: "Multi-day investor connect event",
    organizer: "Apex Venture",
    tags: ["investors", "networking", "multi-day", "venture"],
    notes: "Multi-day event at beautiful estate. Great for deep networking.",
    priority: "high",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: true,
  },
  {
    name: "Hello Tomorrow Summit 2026",
    type: "conference",
    startDate: new Date("2026-06-11"),
    endDate: new Date("2026-06-12"),
    time: "09:00-17:00",
    location: "Amsterdam",
    venue: "NDSM Producties",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/hello-tomorrow-summit-2026",
    cost: "€500-1000+",
    expectedAudience: "1000+ deep tech founders, investors",
    loreWeaverScore: 8,
    loreWeaverReason: "Deep tech focus, relevant for AI/gaming intersection",
    organizer: "Hello Tomorrow",
    tags: ["deeptech", "conference", "innovation", "investors"],
    notes: "Major deep tech summit. Good for AI positioning.",
    priority: "high",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: true,
  },

  // TECH/AI EVENTS
  {
    name: "LET Awards 2026",
    type: "awards",
    startDate: new Date("2026-05-07"),
    time: "16:00-17:00",
    location: "Amsterdam",
    venue: "Westergas, Polonceaukade 9",
    country: "Netherlands",
    website: "https://platform.techleap.nl/events/save-the-date-let-awards-2026",
    cost: "TBA",
    expectedAudience: "300-500 Dutch tech leaders",
    loreWeaverScore: 8,
    loreWeaverReason: "Dutch tech leadership awards, great visibility",
    organizer: "Techleap",
    tags: ["awards", "leadership", "techleap", "visibility"],
    notes: "Celebrating Dutch tech leaders. Great for visibility.",
    priority: "high",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: false,
  },
  {
    name: "AI Compute Summit",
    type: "conference",
    startDate: new Date("2026-05-19"),
    time: "09:00-17:00",
    location: "Amsterdam",
    venue: "Renaissance Amsterdam Hotel",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/ai-compute-summit",
    cost: "TBA",
    expectedAudience: "300+ AI professionals",
    loreWeaverScore: 7,
    loreWeaverReason: "Technical AI focus, on-device inference relevance",
    organizer: "Startup Amsterdam",
    tags: ["ai", "compute", "technical", "conference"],
    notes: "Technical AI focus. Relevant for Director's on-device inference story.",
    priority: "medium",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },
  {
    name: "Deep Tech Days 2026",
    type: "conference",
    startDate: new Date("2026-06-08"),
    endDate: new Date("2026-06-12"),
    time: "09:00-17:00",
    location: "Amsterdam",
    venue: "Multiple locations",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/deep-tech-days-2026",
    cost: "TBA",
    expectedAudience: "500+ deep tech founders & investors",
    loreWeaverScore: 8,
    loreWeaverReason: "Deep tech focus, relevant for Director's technical positioning",
    organizer: "Startup Amsterdam",
    tags: ["deeptech", "conference", "multi-day", "tech"],
    notes: "Week of deep tech events. Good for technical positioning.",
    priority: "high",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: true,
  },
  {
    name: "HumanX EMEA 2026",
    type: "conference",
    startDate: new Date("2026-09-22"),
    endDate: new Date("2026-09-24"),
    time: "09:00-17:00",
    location: "Amsterdam",
    venue: "RAI Amsterdam",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/humanx-emea-2026",
    cost: "TBA",
    expectedAudience: "1000+ AI/human interaction professionals",
    loreWeaverScore: 7,
    loreWeaverReason: "Human-AI interaction focus, very relevant for LoreWeaver vision",
    organizer: "HumanX",
    tags: ["ai", "humanx", "interaction", "conference"],
    notes: "Human-AI interaction focus. Highly relevant for LoreWeaver vision.",
    priority: "high",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: false,
  },

  // FOUNDER/STARTUP EVENTS
  {
    name: "Startup Pitch Event Amsterdam",
    type: "pitch",
    startDate: new Date("2026-04-07"),
    time: "18:00",
    location: "Amsterdam",
    venue: "I Dock",
    country: "Netherlands",
    website: "https://www.eventbrite.com/e/startup-pitch-event-amsterdam-tickets-1317942705109",
    cost: "~€10",
    expectedAudience: "50-100 founders",
    loreWeaverScore: 7,
    loreWeaverReason: "Practice pitch, meet other founders",
    organizer: "Startup Events Amsterdam",
    tags: ["pitch", "startup", "networking", "practice"],
    notes: "Good for pitch practice and founder networking.",
    priority: "medium",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: true,
  },
  {
    name: "AI Tech & Startup Night - Amsterdam",
    type: "meetup",
    startDate: new Date("2026-04-15"),
    time: "18:00",
    location: "Amsterdam",
    venue: "I Dock",
    country: "Netherlands",
    website: "https://www.eventbrite.com/e/ai-tech-startup-night-amsterdam-tickets-1984845699919",
    cost: "~€10",
    expectedAudience: "50-100 AI founders & enthusiasts",
    loreWeaverScore: 8,
    loreWeaverReason: "AI-focused startup community",
    organizer: "Startup Events Amsterdam",
    tags: ["ai", "startup", "networking", "tech"],
    notes: "AI-focused startup networking.",
    priority: "medium",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },
  {
    name: "Monthly Community Drinks at Startup Village",
    type: "meetup",
    startDate: new Date("2026-04-09"),
    time: "17:00",
    location: "Amsterdam",
    venue: "Startup Village",
    country: "Netherlands",
    website: "https://www.eventbrite.nl/e/monthly-community-drinks-kicking-off-with-insight-meet-digital-notary-tickets-1978607769100",
    cost: "Free",
    expectedAudience: "30-50 founders",
    loreWeaverScore: 6,
    loreWeaverReason: "Regular networking opportunity",
    organizer: "Startup Village",
    tags: ["networking", "drinks", "monthly", "startup-village"],
    notes: "Monthly networking at Startup Village.",
    priority: "low",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },
  {
    name: "Hackers & Founders (Amsterdam, NL) Meetup",
    type: "meetup",
    startDate: new Date("2026-04-02"),
    time: "19:00",
    location: "Amsterdam",
    venue: "TBA",
    country: "Netherlands",
    website: "https://www.meetup.com/hackers-and-founders-amsterdam-nl/events/313603259/",
    cost: "Free",
    expectedAudience: "30-50 technical founders",
    loreWeaverScore: 7,
    loreWeaverReason: "Technical founder community",
    organizer: "Hackers & Founders Amsterdam",
    tags: ["technical", "founders", "meetup", "networking"],
    notes: "Technical founder community. Good for product feedback.",
    priority: "medium",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },
  {
    name: "Nursery Presents: From Startup to Scaleup Framework",
    type: "workshop",
    startDate: new Date("2026-04-30"),
    time: "13:00",
    location: "Amsterdam",
    venue: "Startup Village",
    country: "Netherlands",
    website: "https://www.eventbrite.nl/e/nursery-presents-from-startup-to-scaleup-framework-tickets-1985928091381",
    cost: "Free",
    expectedAudience: "30-50 founders",
    loreWeaverScore: 7,
    loreWeaverReason: "Scaling insights",
    organizer: "Startup Village / Nursery",
    tags: ["scaling", "workshop", "framework", "startup-village"],
    notes: "Scaling framework workshop.",
    priority: "medium",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },

  // INDUSTRY EVENTS
  {
    name: "DEVWorld 2026",
    type: "conference",
    startDate: new Date("2026-05-07"),
    endDate: new Date("2026-05-08"),
    time: "09:00-17:00",
    location: "Amsterdam",
    venue: "RAI Amsterdam",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/devworld-2026",
    cost: "€300-600+",
    expectedAudience: "3000+ developers",
    loreWeaverScore: 7,
    loreWeaverReason: "Developer audience, potential Architect users",
    organizer: "DevWorld",
    tags: ["developers", "conference", "tech"],
    notes: "Large developer conference. Potential Architect users.",
    priority: "medium",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },
  {
    name: "IBC 2026 (International Broadcasting Convention)",
    type: "conference",
    startDate: new Date("2026-09-11"),
    endDate: new Date("2026-09-14"),
    time: "09:00-17:00",
    location: "Amsterdam",
    venue: "RAI Amsterdam",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/ibc-2026",
    cost: "€800+",
    expectedAudience: "50000+ media professionals",
    loreWeaverScore: 7,
    loreWeaverReason: "Media/entertainment tech, relevant for game narrative tools",
    organizer: "IBC",
    tags: ["media", "entertainment", "broadcasting", "tech"],
    notes: "Massive media/entertainment tech event. Some gaming overlap.",
    priority: "medium",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },
  {
    name: "TECHSPO Amsterdam 2026",
    type: "conference",
    startDate: new Date("2026-09-17"),
    endDate: new Date("2026-09-18"),
    time: "09:00-17:00",
    location: "Amsterdam",
    venue: "Johan Cruijff ArenA",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/techspo-amsterdam-2026",
    cost: "€200-500",
    expectedAudience: "2000+ tech professionals",
    loreWeaverScore: 6,
    loreWeaverReason: "General tech expo",
    organizer: "TECHSPO",
    tags: ["tech", "expo", "conference"],
    notes: "General tech expo.",
    priority: "low",
    status: "upcoming",
    investorAccess: false,
    pitchOpportunity: false,
  },
  {
    name: "Money20/20 Europe 2026",
    type: "conference",
    startDate: new Date("2026-06-02"),
    endDate: new Date("2026-06-04"),
    time: "09:00-17:00",
    location: "Amsterdam",
    venue: "RAI Amsterdam",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/money20-20-europe-2026",
    cost: "€2000-3000+",
    expectedAudience: "5000+ fintech professionals",
    loreWeaverScore: 6,
    loreWeaverReason: "Fintech focus, some crossover potential",
    organizer: "Money20/20",
    tags: ["fintech", "payments", "banking", "conference"],
    notes: "Major fintech conference. Some crossover potential.",
    priority: "low",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: false,
  },
  {
    name: "Katapult Future Fest 2026",
    type: "conference",
    startDate: new Date("2026-05-27"),
    endDate: new Date("2026-05-29"),
    time: "09:00-17:00",
    location: "Ruigoord",
    venue: "Ruigoord",
    country: "Netherlands",
    website: "https://www.iamsterdam.com/en/business/calendar/events/all/katapult-future-fest-2026",
    cost: "TBA",
    expectedAudience: "1000+ impact innovators",
    loreWeaverScore: 7,
    loreWeaverReason: "Impact/innovation focus",
    organizer: "Katapult",
    tags: ["impact", "innovation", "festival", "future"],
    notes: "Impact innovation festival. Good for storytelling angle.",
    priority: "medium",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: false,
  },

  // NVP EVENTS (VC Association)
  {
    name: "NVP The Next Lunch",
    type: "meetup",
    startDate: new Date("2026-04-10"),
    location: "Netherlands",
    venue: "TBA",
    country: "Netherlands",
    website: "https://nvp.nl/evenementen-overzicht/the-next-lunch/",
    cost: "Free (members only)",
    expectedAudience: "30-50 VCs",
    loreWeaverScore: 7,
    loreWeaverReason: "Direct VC access if can get invite through existing connections",
    organizer: "NVP (Dutch PE/VC Association)",
    tags: ["vc", "networking", "lunch", "nvp"],
    notes: "For NVP member Managing Partners. Need invite through existing connections.",
    priority: "medium",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: false,
  },
  {
    name: "NVP Summer Drinks",
    type: "meetup",
    startDate: new Date("2026-06-18"),
    location: "Netherlands",
    venue: "TBA",
    country: "Netherlands",
    website: "https://nvp.nl/evenementen-overzicht/summerdrinks/",
    cost: "Free (members only)",
    expectedAudience: "100+ VCs & PE professionals",
    loreWeaverScore: 6,
    loreWeaverReason: "VC networking event",
    organizer: "NVP (Dutch PE/VC Association)",
    tags: ["vc", "networking", "drinks", "nvp"],
    notes: "NVP summer networking event.",
    priority: "low",
    status: "upcoming",
    investorAccess: true,
    pitchOpportunity: false,
  },
];

async function seedStartupVCEvents() {
  console.log("Starting Startup & VC events seed...");

  const batch = db.batch();
  const eventsRef = db.collection("events");

  for (const event of startupVCEvents) {
    const docRef = eventsRef.doc();

    const eventData = {
      ...event,
      startDate: Timestamp.fromDate(event.startDate),
      endDate: event.endDate ? Timestamp.fromDate(event.endDate) : null,
      category: "startup-vc",
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
      createdBy: "seed-startup-vc-events",
    };

    batch.set(docRef, eventData);
    console.log(`  Added: ${event.name}`);
  }

  await batch.commit();
  console.log(`\n✅ Successfully seeded ${startupVCEvents.length} startup & VC events!`);
}

// Run the seed
seedStartupVCEvents()
  .then(() => {
    console.log("Seed completed successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Error seeding events:", error);
    process.exit(1);
  });
